url: "https://cs.umanitoba.ca"
baseurl: "/~wics"
sitename: "UM WICS"
locale: "en-US"
permalink: pretty
github: [metadata]

# Generates a sitemap.xml file
plugins:
    - jekyll-sitemap

# Used by jekyll-assets
assets:
    compression: false # Uglify files
    gzip: false
    caching:
        enabled: false
    sources:
        - _assets/
    raw_precompile:
        - src: dist/*
          dst: dist

collections:
    pages: # Keep the root clean organizing all pages into _pages
        output: true
        permalink: /:path/
    co-op-companies:

exclude:
    - README.md
    - scripts
