baseurl: "/~wics"
sitename: "UM WICS"
locale: "en-US"

plugins:
  - jekyll-sitemap

assets:
  compression: true
  gzip: true
  caching:
    enabled: false
  sources:
    - _assets/

collections:
  - co-op-companies
