baseurl: "/~wics"
sitename: "UM WICS"
url: "https://cs.umanitoba.ca/~wics/"
locale: "en-US"
permalink: pretty
github: [metadata]

# Generates a sitemap.xml file
plugins:
    - jekyll-sitemap

# Used by jekyll-assets
assets:
    compression: false # Uglify files
    gzip: true
    caching:
        enabled: false
    sources:
        - _assets/

collections:
    pages: # Keep the root clean organizing all pages into _pages
        output: true
        permalink: /:path/
    co-op-companies:
